### ISSUE TITLE
Compilation problem with VS2015 using Intel Compiler

### ISSUE THREAD

**Issue by Johnex** [libressl-portable/portable#209]
Hi!
I have no issues compiling with the visual studio compiler, but when i build the project using this:

`"C:\Program Files\CMake\bin\cmake.exe" -G"Visual Studio 14 2015" -T"Intel C++ Compiler 16.0" ..`

Then i get hundreds of errors like this one:

> C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_malloc.h(54): error : expected an identifier
>     _ACRTIMP _CRTALLOCATOR _CRTRESTRICT
>                           ^

All errors relate to that corecrt_malloc.h file. I saw that error in one of my projects when i included a header when i shouldn't have, maybe there is a missing ifdef somewhere?

I'm using the latest Visual Studio 2015 Update 2, using Intel C++ Compiler 2016 Update 3

**Comment by busterb** [comment]
I don't have a copy of the Intel C++ compiler, and casual googling didn't find a free source. Any idea where to get it?

**Comment by Johnex** [comment]
You can download the Parallel Studio trial version from here:
https://registrationcenter.intel.com/en/forms/?productid=2490

During the install select just the C++ compiler and you are good to go.

**Comment by Johnex** [comment]
Have you had a chance to look at this issue?
Thanks in advance :)

**Comment by busterb** [comment]
Not yet. I just signed up to download the compiler but haven't heard back.

**Comment by Johnex** [comment]
Hi! I tried to compile using the latest intel compiler, with this updated command:

> cmake.exe" -G"Visual Studio 14 2015" -T"Intel C++ Compiler 17.0" ..

Same issue as before, corecrt_malloc.h errors and nothing compiles :(

Here is a link to the latest Try page for the intel parallel studio 2017, it will give you at least 30 days to see whats wrong with the compilation, while you get the developer license:

https://registrationcenter.intel.com/en/forms/?productid=2490

You get a code instantly in the mail, takes 2 minutes.

**Comment by kinichiro** [comment]
Hi,
I had tried to build with Intel C++ Compiler 17.0 and VS2015.

To prevent these _CRTRESTRICT errors,

```
error : expected an identifier
2>    _ACRTIMP _CRTALLOCATOR _CRTRESTRICT
```

I added `add_definitions(-D_CRT_SUPPRESS_RESTRICT)` to CMakeLists.txt after `if(MSVC)` in the top directory.

After avoiding _CRTRESTRICT errors above, I got this error next while building libtls.

```
1>C:\libressl-2.5.0\tls\tls_util.c(157): error : assertion failed: construct_message: not all fill-ins used (shared/cfe/edgcpfe/error.c, line 3586)
1>
1>    	return (buf);
```

I think this assertion error might be OFF by compiler switch, though, I could not find it.
Then my workaround is cast `buf` by `(uint8_t *)` in tls_load_file() of tls_util.c .

```
	return ((uint8_t *)buf);
```

And undefined PATH_MAX error was the last one while building openssl directory.
My workaround is adding PATH_MAX definition in `include/compat/limits.h`
This issue was posted as https://github.com/libressl-portable/portable/issues/224 .

I could build with these workaround.

Best regards,

**Comment by Johnex** [comment]
I can confirm that the CMakeLists and tls_util.c changes fix compilation :D.
I do see tons of warnings of unused function parameters, a nice way to fix that is to tell the compiler we don't use it like so:

`void foo(int param1, int param2)
{
    (void)param2;
    bar(param1);
}`

Some more warnings are about comparing signed to unsigned values, as well as changing between signed and unsigned in function arguments without casting.

**Comment by Johnex** [comment]
Update, i did not see any error regarding PATH_MAX in my compilation, tried with VS compiler also. @kinichiro could you have a problem with your setup?

**Comment by kinichiro** [comment]
@Johnex
I don't think I have a problem of my setup both Visual Studio and Intel C++ compiler.
I recently clean installed them, and I did not see any errors at that time.
With 2.5.0 tarball and Visual Studio 2015, I always encounter undefined PATH_MAX.
Which version of tarball do you test with ?

About tons of warnings, I think you should disable them by the compiler option rather than modifying source code.
Does this compiler diable warnings by `#pragma warning disable 9999` ?
http://stackoverflow.com/questions/35228509/how-to-disable-warning-using-a-pragma-with-intel-c-compiler
Now, I have no idea how to use this with cmake :-)

BTW, `assertion failed:` while compiling tls_util.c appears to be a bug of Interl C++ compiler, doesn't it ?
I misunderstood that it was a compile error message, though, this should be treated as compile warning.

**Comment by Johnex** [comment]
Yes i see now the same error. I was compiling the tar for 2.4.1. Looking for PATH_MAX here in the repo shows 2 places:

https://github.com/libressl-portable/portable/search?utf8=%E2%9C%93&q=path_max

Something happened between 2.4.1 and 2.5.0 that broke the compilation.

To remove all the errors on Intel i changed this line:

```
	string(REPLACE "C" " -wd" MSVC_DISABLED_WARNINGS_STR
		${MSVC_DISABLED_WARNINGS_LIST})
```

to:

```
	if (CMAKE_C_COMPILER_ID MATCHES "Intel")
		message(STATUS "Using Intel compiler")
		set(MSVC_DISABLED_WARNINGS_LIST "${MSVC_DISABLED_WARNINGS_LIST}"
			"C1786" # Deprecated functions
			"C869"  # Unreferenced parameters
			"C2557" # Comparing signed to unsigned
		)
	endif()
	string(REPLACE "C" " -wd" MSVC_DISABLED_WARNINGS_STR
		${MSVC_DISABLED_WARNINGS_LIST})
```

I think the Intel compiler is more strict with regards to casting from a signed to unsigned variable. The variable was a char pointer , but the function return was an unsigned char pointer. It should be a warning not an error though, you are correct.

**Comment by busterb** [comment]
We generally have the signed vs unsigned warnings disabled for other compilers as well. We've discussed generally changing them, but that also changes the ABI, which is kind of a big thing.

**Comment by Johnex** [comment]
Well ok in that spirit this removes all the current warnings in the intel compiler:

Change:

```
    string(REPLACE "C" " -wd" MSVC_DISABLED_WARNINGS_STR
        ${MSVC_DISABLED_WARNINGS_LIST})
```

To:

```
	if (CMAKE_C_COMPILER_ID MATCHES "Intel")
		message(STATUS "Using Intel compiler")
		set(MSVC_DISABLED_WARNINGS_LIST "${MSVC_DISABLED_WARNINGS_LIST}"
			"C91"   # Unreachable statement
			"C111"  # -"-
			"C128"  # Unreachable loop
			"C164"  # -"-
			"C167"  # Unexplict casting unsigned to signed
			"C186"  # Pointless comparison of unsigned int with zero
			"C188"  # Enumerated type mixed with another type
			"C344"  # Redeclared type
			"C556"  # Unexplict casting signed to unsigned
			"C869"  # Unreferenced parameters
			"C1786" # Deprecated functions
			"C2545" # Empty else statement
			"C2557" # Comparing signed to unsigned
			"C2722" # List init syntax is c++11 feature
			"C3280" # Declaration hides variable
		)
	endif()
	string(REPLACE "C" " -wd" MSVC_DISABLED_WARNINGS_STR
		${MSVC_DISABLED_WARNINGS_LIST})
```

**Comment by Johnex** [comment]
We still have the error with the char to uint8_t cast, and the PATH_MAX unset error.

**Comment by kinichiro** [comment]
Yes, we must keep ABI compatibility, and disabling warning by compiler option is the best way now.

PATH_MAX issue seems to occur only with MSVC, and I posted my suggestion here https://github.com/libressl-portable/portable/issues/224 .

The issue "returning (char *) in `uint8_t *tls_load_file(...)`",
it seems that there is no way other than changing source code.

**Comment by Johnex** [comment]
@busterb, maybe we could add my cmake changes, merge #224 and change the return of the fuction? What do you say? :)

**Comment by Johnex** [comment]
I added a comment to #224, the issue is a problem in CMakeLists, as the declaration exists already.

**Comment by kinichiro** [comment]
I sent patch request about casting to tech ML.
http://marc.info/?l=openbsd-tech&m=147532231431162&w=2

**Comment by Johnex** [comment]
@kinichiro you got a reply in the mailing list. I don't know how to reply to it, but basically its not a bug, the intel compiler is just strict about casting, as buf is a char*, and its being converted to an unsigned char*.

**Comment by Johnex** [comment]
So turns out it was a compiler bug, you got a reply to your thread @kinichiro :)

https://software.intel.com/en-us/forums/intel-c-compiler/topic/698109#comment-1886511

**Comment by kinichiro** [comment]
@Johnex Yes we could have an answer for that.
And source code has already fixed by this commit.
https://github.com/libressl-portable/openbsd/commit/460539c1b7af5fdf9c0583cea74be08f8dd4fcea

**Comment by kinichiro** [comment]
I created the patch for this issue.
https://github.com/libressl-portable/portable/compare/master...kinichiro:fix_intel
If this is OK, I would like to post this as Pull Request.
This patch does not include the solution of PATH_MAX since that is another issue.

**Comment by Johnex** [comment]
Looks great and works as it should 👍.
I like how you modified the compiler printout too :metal:

**Comment by kinichiro** [comment]
I removed "C91" and "C164" since these 2 warnings are not occurred with Intel C++ 17.0.

**Comment by Johnex** [comment]
You are right about the 2 warnings. Strange but i did see them when i tested having no IF for the other vs compiler warnings, maybe that caused more warnings to appear....

**Comment by busterb** [comment]
This should be working with #233, thanks @kinichiro
