### ISSUE TITLE
v2.4.4 on OSX: linking error (getentropy)

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#230]
This is OS X 10.11.6 with non-Apple clang 3.9
## Evidence of issue

compat/arc4random.c:90:6: warning: implicit declaration of function 'getentropy' is invalid in C99 [-Wimplicit-function-declaration]
        if (getentropy(rnd, sizeof rnd) == -1)
            ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_getentropy", referenced from:
      __rs_stir_if_needed in libcompat.a(arc4random.o)
ld: symbol(s) not found for architecture x86_64
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: **\* [libcrypto.la] Error 1
make: **\* [all-recursive] Error 1

**Comment by busterb** [comment]
So, from homebrew?

**Comment by hdatma** [comment]
From source.

**Comment by hdatma** [comment]
Libressl is in good company: many libraries fail to compile with the new xcode 8 on OS X 10.11.6.

**Comment by hdatma** [comment]
I strongly advise anyone to refrain from upgrading to xcode 8.

**Comment by hdatma** [comment]
I am downgrading to xcode 7.3.1 from https://developer.apple.com/download/more/
It will take a while. Will be back with the results for libressl.

**Comment by busterb** [comment]
I have xcode 8.0.0 and libressl builds fine on 10.12. I'm wondering if they accidentally included the getentropy headers on 10.11's build of xcode 8.0.0, but it's not actually implemented in the libc, causing the issue. If so, we might need to improve the getentropy check in libressl.

**Comment by hdatma** [comment]
I am back to xcode 3.7.1 on 10.11.6 and it builds with neither errors nor warnings. Just perfect.

**Comment by leonklingele** [comment]
Works fine for me on 10.11.6 + Xcode 8.

**Comment by hdatma** [comment]
leonklingele:
are you on xcode 8.0.0 or pre-8.0.1? 
are you on official (non-apple) llvm 3.9 ?
did you use homebrew?

**Comment by DomT4** [comment]
> So, from homebrew?

Homebrew suppresses a lot of warnings because mostly for users they're of little value and would kill builds all over the place, especially given Clang can be pretty fussy. From our build process for `libressl`, for example:

```
clang called with: -g -O2 -Wall -std=gnu99 -fno-strict-aliasing -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Qunused-arguments -Wno-pointer-sign -Qunused-arguments -o .libs/utf8test utf8test.o /private/tmp/libressl-20160930-57372-1akok5i/libressl-2.4.3/tls/.libs/libtls.dylib /private/tmp/libressl-20160930-57372-1akok5i/libressl-2.4.3/ssl/.libs/libssl.dylib /private/tmp/libressl-20160930-57372-1akok5i/libressl-2.4.3/crypto/.libs/libcrypto.dylib
superenv removed:  -g -O2 -Wall
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
superenv executed: clang -pipe -w -Os -march=native -std=gnu99 -fno-strict-aliasing -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Qunused-arguments -Wno-pointer-sign -Qunused-arguments -o .libs/utf8test utf8test.o /private/tmp/libressl-20160930-57372-1akok5i/libressl-2.4.3/tls/.libs/libtls.dylib /private/tmp/libressl-20160930-57372-1akok5i/libressl-2.4.3/ssl/.libs/libssl.dylib /private/tmp/libressl-20160930-57372-1akok5i/libressl-2.4.3/crypto/.libs/libcrypto.dylib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
```

**Comment by leonklingele** [comment]
@hdatma Xcode 8.0 (8A218a), clang version 3.8.1 (from Homebrew, unbottled version, i.e. `--build-from-source`).

**Comment by hdatma** [comment]
>uname -a
Darwin alice.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64

>xcode-select -v    
xcode-select version 2345.1.

>clang -v
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /opt/llvm/bin

>openssl version
LibreSSL 2.4.4

compat/arc4random.c:90:6: warning: implicit declaration of function 'getentropy' is invalid in C99 [-Wimplicit-function-declaration]
        if (getentropy(rnd, sizeof rnd) == -1)
            ^

**Comment by hdatma** [comment]
> Don't use arc4random on systems before 10.12 because of [...]
Ref. https://github.com/libressl-portable/portable/commit/a206997ad9b7ebd4bb383b10212f02e26f924e56

I am using 10.12.2 with xcode 8.2.1. This is the output:

compat/arc4random.c:90:6: warning: implicit declaration of function 'getentropy' is invalid in C99 [-Wimplicit-function-declaration]
        if (getentropy(rnd, sizeof rnd) == -1)
            ^
1 warning generated.

**Comment by hdatma** [comment]
Closing as fixed.
