### ISSUE TITLE
clock_gettime detection fails

### ISSUE THREAD

**Issue by dirkvdb** [libressl-portable/portable#416]
After upgrading from 2.6.4 to 2.7.2 the build fails on my setup because HAVE_CLOCK_GETTIME is not properly detected.

The build fails with the following error
```
usr/include/time.h:336:12: error: conflicting types for 'clock_gettime'
 extern int clock_gettime (clockid_t __clock_id, struct timespec *__tp) __THROW;
```
because HAVE_CLOCK_GETTIME is not defined.

This is the reason why it fails
```
check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)
if(HAVE_CLOCK_GETTIME)
	add_definitions(-DHAVE_CLOCK_GETTIME)
endif()

if(CMAKE_SYSTEM_NAME MATCHES "Linux")
	check_library_exists(rt clock_gettime "time.h" HAVE_CLOCK_GETTIME)
	if (HAVE_CLOCK_GETTIME)
		set(OPENSSL_LIBS ${OPENSSL_LIBS} rt)
	endif()
	set(OPENSSL_LIBS ${OPENSSL_LIBS} pthread)
endif()
```

After the first check (check_function_exists) the HAVE_CLOCK_GETTIME variable is set to false in the cmake cache. Then when clock_gettime is searched for in the rt library using check_library_exists, no check is performed since cmake already has a value in the cache for HAVE_CLOCK_GETTIME

Line 35 in
[https://github.com/Kitware/CMake/blob/master/Modules/CheckLibraryExists.cmake](https://github.com/Kitware/CMake/blob/master/Modules/CheckLibraryExists.cmake)

So the HAVE_CLOCK_GETTIME variable should be cleared befored the call to check_function_exists if it is false, otherwise no check is performed.
Something like
```
if (NOT HAVE_CLOCK_GETTIME)
    unset(HAVE_CLOCK_GETTIME CACHE)
endif ()
```

**Comment by busterb** [comment]
Would it make more sense to move rename the second 'HAVE_CLOCK_GETTIME' to 'CLOCK_GETTIME_NEED_RT' ?

**Comment by dirkvdb** [comment]
That seems to make more sense yes.

But for it to work on my system, it would have to look like this:
```
check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)
if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    check_library_exists(rt clock_gettime "time.h" CLOCK_GETTIME_NEED_RT)
    if (CLOCK_GETTIME_NEED_RT)
        set(OPENSSL_LIBS ${OPENSSL_LIBS} rt)
    endif()
    set(OPENSSL_LIBS ${OPENSSL_LIBS} pthread)
endif()

if(HAVE_CLOCK_GETTIME OR CLOCK_GETTIME_NEED_RT)
    add_definitions(-DHAVE_CLOCK_GETTIME)
endif()
```
because the check_function_exists call fails on my setup because it gets a linker error as it requires the -lrt flag

**Comment by dirkvdb** [comment]
That would work for me
