### ISSUE TITLE
2.8.0 release doesn't compile with nginx

### ISSUE THREAD

**Issue by leonklingele** [libressl-portable/portable#435]
LibreSSL (2.8.0) doesn't compile with nginx 1.15.2 (static build). Compilation worked fine with 2.7.4.
Seems like an inadvertent API change.

```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fdebug-prefix-map=/packaging/nginx/upstream=. -fstack-protector-strong -Wformat -Werror=format-security -I src/core -I src/event -I src/event/modules -I src/os/unix -I submodules/pcre -I submodules/libressl/.openssl/include -I objs \
	-o objs/src/event/ngx_event_openssl.o \
	src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_session_cache’:
src/event/ngx_event_openssl.c:2340:43: error: passing argument 2 of ‘SSL_CTX_sess_set_get_cb’ from incompatible pointer type [-Werror=incompatible-pointer-types]
         SSL_CTX_sess_set_get_cb(ssl->ctx, ngx_ssl_get_cached_session);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/event/ngx_event_openssl.h:15:0,
                 from src/core/ngx_core.h:83,
                 from src/event/ngx_event_openssl.c:9:
submodules/libressl/.openssl/include/openssl/ssl.h:729:6: note: expected ‘SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, const unsigned char *, int,  int *)}’ but argument is of type ‘SSL_SESSION * (*)(SSL *, u_char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, unsigned char *, int,  int *)}’
 void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
      ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by 4a6f656c** [comment]
The `SSL_CTX_sess_set_get_cb()` function (among many others) has been changed in LibreSSL 2.8.0, so that the call back signature has const, which matches the (current) OpenSSL API. Unfortunately, applications tend to condition on version numbers and define their functions with or without const accordingly.

It seems that nginx decided to #undef and redefine `OPENSSL_VERSION_NUMBER` when LibreSSL is in use, mapping it to an older OpenSSL version:

https://github.com/nginx/nginx/blob/master/src/event/ngx_event_openssl.h#L37

This means that the const does not get included in the function [prototype](https://github.com/nginx/nginx/blob/branches/stable-1.14/src/event/ngx_event_openssl.c#L42) or [declaration](https://github.com/nginx/nginx/blob/branches/stable-1.14/src/event/ngx_event_openssl.c#L2596) and is mismatched, hence the warning.

Your options are probably to ignore the const-related warning or patch the code to use `LIBRESSL_VERSION_NUMBER` to handle this correctly: 

```
#if OPENSSL_VERSION_NUMBER >= 0x10100003L || \
    (defined(LIBRESSL_VERSION_NUMBER) && LIBRESSL_VERSION_NUMBER >= 0x2080000fL
    const
#endif
```

You may also be able to increase the `OPENSSL_VERSION_NUMBER` that they use for LibreSSL, although I'm not sure if that will cause other problems (since there is no 1:1 mapping between the APIs - hence a separate version number existing).

I'd also suggest reporting this upstream to nginx, since it will need to be fixed there at some point.

**Comment by botovq** [comment]
For what it's worth: OpenBSD's nginx port (still at 1.14.0) builds without LibreSSL-related warnings when undoing the #undef hack introduced in [this commit](https://github.com/nginx/nginx/commit/bad99ee0047282fd5a8e5730d440a032eb2452ed). The reasoning in the commit message seems no longer relevant: the explicit version number checks that it hid were replaced with the[X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT toggle](https://github.com/nginx/nginx/commit/3c44339bfed78c9ad3549edf2b7408c15d3ae51c) half a year later.

Hopefully, they will reconsider this.
