### ISSUE TITLE
libressl 2.7.0 build fails on macOS 10.11 (El Capitan)

### ISSUE THREAD

**Issue by fxcoudert** [libressl-portable/portable#411]
libressl 2.7.0 does not build on macOS 10.11 (El Capitan) with the following error:

```
apps_posix.c:132:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_MONOTONIC, &now);
                      ^
../../include/compat/sys/time.h:17:25: note: expanded from macro 'CLOCK_MONOTONIC'
#define CLOCK_MONOTONIC CLOCK_REALTIME
```

Failure was discovered in testing the 2.7.0 release for Homebrew: https://github.com/Homebrew/homebrew-core/pull/25615

**Comment by kinichiro** [comment]
Same report on ML.
https://marc.info/?l=libressl&m=152173540030300&w=2
