### PR TITLE
add clock_gettime for macos 10.11 and earlier

### LINKED ISSUE #411: libressl 2.7.0 build fails on macOS 10.11 (El Capitan)
libressl 2.7.0 does not build on macOS 10.11 (El Capitan) with the following error:

```
apps_posix.c:132:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_MONOTONIC, &now);
                      ^
../../include/compat/sys/time.h:17:25: note: expanded from macro 'CLOCK_MONOTONIC'
#define CLOCK_MONOTONIC CLOCK_REALTIME
```

Failure was discovered in testing the 2.7.0 release for Homebrew: https://github.com/Homebrew/homebrew-core/pull/25615

### PR DESCRIPTION
**Pull request by busterb**
This should fix #411 on earlier versions of macos. I haven't added the cmake bits yet and this needs a bit more testing.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The build fails on 10.11

```
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DPACKAGE_NAME=\"libressl\" -DPACKAGE_TARNAME=\"libressl\" -DPACKAGE_VERSION=\"2.7.1\" -DPACKAGE_STRING=\"libressl\ 2.7.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libressl\" -DVERSION=\"2.7.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_SYMLINK=1 -DHAVE_ERR_H=1 -DHAVE_READPASSPHRASE_H=1 -DHAVE_ASPRINTF=1 -DHAVE_MEMMEM=1 -DHAVE_READPASSPHRASE=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRNLEN=1 -DHAVE_STRSEP=1 -DHAVE_TIMEGM=1 -DHAVE_POLL=1 -DHAVE_SOCKETPAIR=1 -DHAVE_ARC4RANDOM=1 -DHAVE_ARC4RANDOM_BUF=1 -DHAVE_ARC4RANDOM_UNIFORM=1 -DHAVE_VA_COPY=1 -DHAVE___VA_COPY=1 -DSIZEOF_TIME_T=8 -I.  -I../include -I../include/compat -DLIBRESSL_INTERNAL -D__BEGIN_HIDDEN_DECLS= -D__END_HIDDEN_DECLS= -I../crypto/asn1 -I../crypto/bn -I../crypto/evp -I../crypto/modes -I../crypto -DLIBRESSL_INTERNAL -DOPENSSL_NO_HW_PADLOCK   -DOPENSSLDIR=\"/usr/local/etc/libressl\"   -DAES_ASM -DBSAES_ASM -DVPAES_ASM -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DMD5_ASM -DGHASH_ASM -DRSA_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DWHIRLPOOL_ASM -DOPENSSL_CPUID_OBJ   -g -O2 -Wall -std=gnu99 -fno-strict-aliasing  -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-strong  -Qunused-arguments -Wno-pointer-sign -c -o libcrypto_la-crypto_init.lo `test -f 'crypto_init.c' || echo './'`crypto_init.c
libtool: compile:  clang -DPACKAGE_NAME=\"libressl\" -DPACKAGE_TARNAME=\"libressl\" -DPACKAGE_VERSION=\"2.7.1\" "-DPACKAGE_STRING=\"libressl 2.7.1\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libressl\" -DVERSION=\"2.7.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_SYMLINK=1 -DHAVE_ERR_H=1 -DHAVE_READPASSPHRASE_H=1 -DHAVE_ASPRINTF=1 -DHAVE_MEMMEM=1 -DHAVE_READPASSPHRASE=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRNLEN=1 -DHAVE_STRSEP=1 -DHAVE_TIMEGM=1 -DHAVE_POLL=1 -DHAVE_SOCKETPAIR=1 -DHAVE_ARC4RANDOM=1 -DHAVE_ARC4RANDOM_BUF=1 -DHAVE_ARC4RANDOM_UNIFORM=1 -DHAVE_VA_COPY=1 -DHAVE___VA_COPY=1 -DSIZEOF_TIME_T=8 -I. -I../include -I../include/compat -DLIBRESSL_INTERNAL -D__BEGIN_HIDDEN_DECLS= -D__END_HIDDEN_DECLS= -I../crypto/asn1 -I../crypto/bn -I../crypto/evp -I../crypto/modes -I../crypto -DLIBRESSL_INTERNAL -DOPENSSL_NO_HW_PADLOCK -DOPENSSLDIR=\"/usr/local/etc/libressl\" -DAES_ASM -DBSAES_ASM -DVPAES_ASM -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DMD5_ASM -DGHASH_ASM -DRSA_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DWHIRLPOOL_ASM -DOPENSSL_CPUID_OBJ -g -O2 -Wall -std=gnu99 -fno-strict-aliasing -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Qunused-arguments -Wno-pointer-sign -c crypto_init.c  -fno-common -DPIC -o .libs/libcrypto_la-crypto_init.o
In file included from crypto_init.c:19:
In file included from ../include/compat/pthread.h:61:
In file included from /usr/include/pthread.h:60:
../include/compat/time.h:36:15: error: unknown type name 'clockid_t'; did you mean 'clock_t'?
clock_gettime(clockid_t clock_id, struct timespec *tp);
              ^
/usr/include/sys/_types/_clock_t.h:30:33: note: 'clock_t' declared here
typedef __darwin_clock_t        clock_t;
                                ^
In file included from crypto_init.c:22:
In file included from ../include/openssl/objects.h:960:
In file included from ../include/openssl/asn1.h:62:
../include/compat/time.h:36:15: error: unknown type name 'clockid_t'; did you mean 'clock_t'?
clock_gettime(clockid_t clock_id, struct timespec *tp);
              ^~~~~~~~~
              clock_t
/usr/include/sys/_types/_clock_t.h:30:33: note: 'clock_t' declared here
typedef __darwin_clock_t        clock_t;
                                ^
2 errors generated.
make[2]: *** [libcrypto_la-crypto_init.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

https://gist.github.com/ilovezfs/28e51ecccbb0c376204830916abe0410

**Comment by ilovezfs** [comment]
Also, note that on a system that has only Xcode.app and does not have the separate Command Line Tools package, the build will succeed but make check will fail with
```
bash-3.2$ ./tests/timingsafe
dyld: lazy symbol binding failed: Symbol not found: _timingsafe_bcmp
  Referenced from: /private/tmp/libressl-20180323-15712-1epfsd9/./tests/timingsafe
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _timingsafe_bcmp
  Referenced from: /private/tmp/libressl-20180323-15712-1epfsd9/./tests/timingsafe
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
bash-3.2$ 
```

**Comment by ilovezfs** [comment]
>I don't think we can support systems that do not have the command line tools installed. What is your use case for not installing them?

As of https://github.com/Homebrew/brew/pull/3453, for Homebrew we only support a CLT-less system for macOS 10.13 (or going forward, whatever the latest version of macOS is) so a CLT-less OS X 10.11 system is no longer a use case that affects us directly. That said, this can be handled correctly if you do wish to support it. See e.g. https://github.com/pyca/cryptography/pull/3841

**Comment by busterb** [comment]
Got it, thanks. Will see what we can do to support it.

**Comment by ilovezfs** [comment]
Fixes looks good with Autotools: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/20936/

It's failing with CMake though.
```
cd /tmp/libressl-20180323-89842-522dof/libressl-2.7.0/apps/openssl && /usr/local/Cellar/cmake/3.10.3/bin/cmake -E cmake_link_script CMakeFiles/openssl.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/openssl.dir/apps.c.o CMakeFiles/openssl.dir/asn1pars.c.o CMakeFiles/openssl.dir/ca.c.o CMakeFiles/openssl.dir/ciphers.c.o CMakeFiles/openssl.dir/crl.c.o CMakeFiles/openssl.dir/crl2p7.c.o CMakeFiles/openssl.dir/dgst.c.o CMakeFiles/openssl.dir/dh.c.o CMakeFiles/openssl.dir/dhparam.c.o CMakeFiles/openssl.dir/dsa.c.o CMakeFiles/openssl.dir/dsaparam.c.o CMakeFiles/openssl.dir/ec.c.o CMakeFiles/openssl.dir/ecparam.c.o CMakeFiles/openssl.dir/enc.c.o CMakeFiles/openssl.dir/errstr.c.o CMakeFiles/openssl.dir/gendh.c.o CMakeFiles/openssl.dir/gendsa.c.o CMakeFiles/openssl.dir/genpkey.c.o CMakeFiles/openssl.dir/genrsa.c.o CMakeFiles/openssl.dir/nseq.c.o CMakeFiles/openssl.dir/ocsp.c.o CMakeFiles/openssl.dir/openssl.c.o CMakeFiles/openssl.dir/passwd.c.o CMakeFiles/openssl.dir/pkcs12.c.o CMakeFiles/openssl.dir/pkcs7.c.o CMakeFiles/openssl.dir/pkcs8.c.o CMakeFiles/openssl.dir/pkey.c.o CMakeFiles/openssl.dir/pkeyparam.c.o CMakeFiles/openssl.dir/pkeyutl.c.o CMakeFiles/openssl.dir/prime.c.o CMakeFiles/openssl.dir/rand.c.o CMakeFiles/openssl.dir/req.c.o CMakeFiles/openssl.dir/rsa.c.o CMakeFiles/openssl.dir/rsautl.c.o CMakeFiles/openssl.dir/s_cb.c.o CMakeFiles/openssl.dir/s_client.c.o CMakeFiles/openssl.dir/s_server.c.o CMakeFiles/openssl.dir/s_socket.c.o CMakeFiles/openssl.dir/s_time.c.o CMakeFiles/openssl.dir/sess_id.c.o CMakeFiles/openssl.dir/smime.c.o CMakeFiles/openssl.dir/speed.c.o CMakeFiles/openssl.dir/spkac.c.o CMakeFiles/openssl.dir/ts.c.o CMakeFiles/openssl.dir/verify.c.o CMakeFiles/openssl.dir/version.c.o CMakeFiles/openssl.dir/x509.c.o CMakeFiles/openssl.dir/apps_posix.c.o CMakeFiles/openssl.dir/certhash.c.o CMakeFiles/openssl.dir/compat/strtonum.c.o  -o openssl ../../tls/libtls.a ../../ssl/libssl.a ../../crypto/libcrypto.a 
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _app_timer_real in apps_posix.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Full log: https://gist.github.com/ilovezfs/1e48cf253b4400f135b9b1e2f38d25a1

**Comment by busterb** [comment]
Thanks, our continuous integration test caught it too. Just pushed an update that will hopefully address both versions.

**Comment by busterb** [comment]
I'm going to go ahead and merge this for 2.7.1, outside of that possible issue with CLT-less systems

**Comment by ilovezfs** [comment]
Thanks @busterb! By the way, as in https://github.com/libressl-portable/portable/issues/370, https://www.libressl.org/ still says 2.6.4 not 2.7.1

**Comment by ilovezfs** [comment]
OK, I've reverted 2.7.1 in Homebrew.
