### ISSUE TITLE
build failed due to openbsd change

### ISSUE THREAD

**Issue by braindevices** [libressl-portable/portable#656]
```
ssl_lib.c:(.text+0xd40): multiple definition of `SSL_is_dtls'; CMakeFiles/openssl.dir/apps.c.o:apps.c:(.text+0x4880): first defined here
```

caused by https://github.com/libressl-portable/openbsd/commit/b1b4449fe199f281c443e7d761f29036a3089224

**Comment by busterb** [comment]
Addressed for now in https://github.com/libressl-portable/openbsd/commit/56d68825ab017cee1632ac5545bf2e651960f77b, thanks.
