### ISSUE TITLE
libssh2 build failed: crypt.c:71:25: error: field ‘h’ has incomplete type

### ISSUE THREAD

**Issue by abcfy2** [libressl-portable/portable#736]
Full log can be found here: https://github.com/abcfy2/aria2-static-build/runs/5341821349?check_suite_focus=true

```sh
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking for sed... /usr/bin/sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mips64-linux-musl-strip... mips64-linux-musl-strip
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking libssh2 version... 1.10.0
checking build system type... x86_64-pc-linux-gnu
checking host system type... mips64-unknown-linux-musl
configure: autobuild project... libssh2
configure: autobuild revision... 1.10.0
configure: autobuild hostname... 2eaabde2e5cf
configure: autobuild timestamp... 20220226-022944
checking whether make supports the include directive... yes (GNU style)
checking for mips64-linux-musl-gcc... mips64-linux-musl-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether mips64-linux-musl-gcc accepts -g... yes
checking for mips64-linux-musl-gcc option to enable C11 features... none needed
checking whether mips64-linux-musl-gcc understands -c and -o together... yes
checking dependency style of mips64-linux-musl-gcc... gcc3
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for long long... yes
checking if _REENTRANT is already defined... no
checking if _REENTRANT is actually needed... no
checking if _REENTRANT is onwards defined... no
checking for library containing socket... none required
checking for library containing inet_addr... none required
checking for mips64-linux-musl-gcc... (cached) mips64-linux-musl-gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether mips64-linux-musl-gcc accepts -g... (cached) yes
checking for mips64-linux-musl-gcc option to enable C11 features... (cached) none needed
checking whether mips64-linux-musl-gcc understands -c and -o together... (cached) yes
checking dependency style of mips64-linux-musl-gcc... (cached) gcc3
checking for mips64-linux-musl-g++... mips64-linux-musl-g++
checking whether the compiler supports GNU C++... yes
checking whether mips64-linux-musl-g++ accepts -g... yes
checking for mips64-linux-musl-g++ option to enable C++11 features... none needed
checking dependency style of mips64-linux-musl-g++... gcc3
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for sshd... no
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by mips64-linux-musl-gcc... /cross_root/mips64-linux-musl/bin/ld
checking if the linker (/cross_root/mips64-linux-musl/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /cross_root/bin/mips64-linux-musl-nm -B
checking the name lister (/cross_root/bin/mips64-linux-musl-nm -B) interface... BSD nm
checking the maximum length of command line arguments... 3145728
checking how to convert x86_64-pc-linux-gnu file names to mips64-unknown-linux-musl format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /cross_root/mips64-linux-musl/bin/ld option to reload object files... -r
checking for mips64-linux-musl-objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for mips64-linux-musl-dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for mips64-linux-musl-ar... mips64-linux-musl-ar
checking for archiver @FILE support... @
checking for mips64-linux-musl-strip... (cached) mips64-linux-musl-strip
checking for mips64-linux-musl-ranlib... mips64-linux-musl-ranlib
checking command to parse /cross_root/bin/mips64-linux-musl-nm -B output from mips64-linux-musl-gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mips64-linux-musl-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if mips64-linux-musl-gcc supports -fno-rtti -fno-exceptions... no
checking for mips64-linux-musl-gcc option to produce PIC... -fPIC -DPIC
checking if mips64-linux-musl-gcc PIC flag -fPIC -DPIC works... yes
checking if mips64-linux-musl-gcc static flag -static works... yes
checking if mips64-linux-musl-gcc supports -c -o file.o... yes
checking if mips64-linux-musl-gcc supports -c -o file.o... (cached) yes
checking whether the mips64-linux-musl-gcc linker (/cross_root/mips64-linux-musl/bin/ld -m elf64btsmip) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... mips64-linux-musl-g++ -E
checking for ld used by mips64-linux-musl-g++... /cross_root/mips64-linux-musl/bin/ld -m elf64btsmip
checking if the linker (/cross_root/mips64-linux-musl/bin/ld -m elf64btsmip) is GNU ld... yes
checking whether the mips64-linux-musl-g++ linker (/cross_root/mips64-linux-musl/bin/ld -m elf64btsmip) supports shared libraries... yes
checking for mips64-linux-musl-g++ option to produce PIC... -fPIC -DPIC
checking if mips64-linux-musl-g++ PIC flag -fPIC -DPIC works... yes
checking if mips64-linux-musl-g++ static flag -static works... yes
checking if mips64-linux-musl-g++ supports -c -o file.o... yes
checking if mips64-linux-musl-g++ supports -c -o file.o... (cached) yes
checking whether the mips64-linux-musl-g++ linker (/cross_root/mips64-linux-musl/bin/ld -m elf64btsmip) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether byte ordering is bigendian... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for ld used by GCC... /cross_root/mips64-linux-musl/bin/ld -m elf64btsmip
checking if the linker (/cross_root/mips64-linux-musl/bin/ld -m elf64btsmip) is GNU ld... yes
checking for shared library run path origin... done
checking for libssl... yes
checking how to link with libssl... /cross_root/mips64-linux-musl/lib/libssl.a /cross_root/mips64-linux-musl/lib/libcrypto.a
checking for EVP_aes_128_ctr... yes
checking for mips64-linux-musl-gcc options needed to detect all undeclared functions... none needed
checking for libz... yes
checking how to link with libz... /cross_root/mips64-linux-musl/lib/libz.a
configure: WARNING: secure clearing/zeroing of memory is not supported by the selected crypto backend
checking whether to enable pedantic and debug compiler options... checking how to run the C preprocessor... mips64-linux-musl-gcc -E
no
checking whether to enable hidden symbols in the library... no
checking whether to build example applications... yes
checking for errno.h... yes
checking for fcntl.h... yes
checking for stdio.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/uio.h... yes
checking for sys/select.h... yes
checking for sys/socket.h... yes
checking for sys/ioctl.h... yes
checking for sys/time.h... yes
checking for arpa/inet.h... yes
checking for netinet/in.h... yes
checking for sys/un.h... yes
checking for windows.h... no
checking for winsock2.h... no
checking for ws2tcpip.h... no
checking for poll... yes
checking for gettimeofday... yes
checking for select... yes
checking for strtoll... yes
checking for memset_s... no
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking non-blocking sockets style... O_NONBLOCK
checking whether to enable compiler warnings as errors... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating tests/ossfuzz/Makefile
config.status: creating example/Makefile
config.status: creating docs/Makefile
config.status: creating libssh2.pc
config.status: creating src/libssh2_config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: summary of build options:

  version:          1.10.0
  Host type:        mips64-unknown-linux-musl
  Install prefix:   /cross_root/mips64-linux-musl
  Compiler:         mips64-linux-musl-gcc
  Compiler flags:   -g -O2
  Library types:    Shared=no, Static=yes
  Crypto library:   OpenSSL (AES-CTR: yes)
  Clear memory:     unsupported
  Debug build:      no
  Build examples:   yes
  Path to sshd:      (only for self-tests)
  zlib compression: yes

Making all in src
make[1]: Entering directory '/usr/src/libssh2/src'
make  all-am
make[2]: Entering directory '/usr/src/libssh2/src'
  CC       comp.lo
  CC       channel.lo
  CC       crypt.lo
crypt.c:71:25: error: field ‘h’ has incomplete type
   71 |     _libssh2_cipher_ctx h;
      |                         ^
make[2]: *** [Makefile:611: crypt.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:468: all] Error 2
make[2]: Leaving directory '/usr/src/libssh2/src'
make[1]: Leaving directory '/usr/src/libssh2/src'
make: *** [Makefile:554: all-recursive] Error 1
```

**Comment by botovq** [comment]
On Sat, Feb 26, 2022 at 01:05:20AM -0800, Feng Yu wrote:
> But old version does not require this option, what happened ? Will you fix this issue in the feature?

HMAC_CTX is now opaque as it has been for a long time in OpenSSL 1.1.
This will have to be fixed in libssh2, i.e., they should use this option
for builds with LibreSSL >= 2.7

The !defined(LIBRESSL_VERSION_NUMBER) in

https://github.com/libssh2/libssh2/blob/17c9c1fcdf48ea033a307ce77c432f039ead4584/src/openssl.h#L97

should be removed.

**Comment by abcfy2** [comment]
OK. I'll submit this issue to libssh2. Thanks.
